### ISSUE TITLE
consider pinning scip/gurobi deps

### ISSUE THREAD

**Issue by tlambert03** [funkelab/ilpy#48]
It looks like both scip and gurobi recently updated, and now the current ilpy build doesn't work because it was built against different versions of the lib.  I guess that means we should probably be hard pinning the deps in our [feedstock](https://github.com/funkelab/ilpy-feedstock)?   I do believe conda has the ability to negotiate build versions with other libraries in the environment... but to bring back general compatibility with multiple versions of gurobi/scip, we likely need to do more work

**Comment by tlambert03** [comment]
will try to fix today.  but for now, you should be able to downgrade scip and/or gurobi to whatever version they were on about a month ago

**Comment by tlambert03** [comment]
fix is building now ... should upload within 30 mins or so if all goes well: https://github.com/funkelab/ilpy-feedstock/actions/runs/7145657428

**Comment by bentaculum** [comment]
Thanks a lot, installation is working fine again :)

**Comment by tlambert03** [comment]
Thanks!
