### ISSUE TITLE
Conda install error for python 3.8

### ISSUE THREAD

**Issue by cmalinmayor** [funkelab/ilpy#60]
@tlambert03 CI failed when I merged the autoupdate PR. It seems like the conda on macos-latest doesn't hold a gurobi that is compatible with python 3.8. Should we just stop supporting/testing 3.8? Pin the macos version? Something else?
https://github.com/funkelab/ilpy/actions/runs/8882608765/job/24387679572

**Comment by tlambert03** [comment]
it's likely due to the recent change in the macos-latest runner on github (a couple weeks ago they moved to silicon-based runners and it requires a number of changes to be made).  fixing in #61
